account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name="account/logout.html"), name="logout"),
    path("register/", views.SignUp, name="signup"),
    path("", views.home, name="home"),
    path("aboutus/", views.aboutus, name="about-us"),
    path("contact/", views.contact, name="contact"),
]

appointment/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "appointment"

urlpatterns = [
    path("appointments/p/", views.AppointmentsForAPatientView.as_view(), name="patient-appointments"),
    path("appointments/d/", views.AppointmentsForADoctorView.as_view(), name="doctor-appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med-history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doc-prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc-prescriptions-create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment-create"),
    path("rdashboard/", views.rdashboard, name="r_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
    path("hraccounting/", views.hraccounting, name="hr_accounting"),
    path("payments/", views.pateintpayments, name="pat_payments"),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('account.urls', namespace="account")),
    path("", include('user_profile.urls', namespace="user_profile")),
    path("", include('appointment.urls', namespace="appointment")),
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UpdatedUserProfile, name="profile"),
    path("profile/create/", views.CreateUserProfile, name="profile-create"),
    path("profile/<int:pk>/", views.UpdatedUserProfilePk, name="profile-pk"),
    path("profile/doc/<int:pk>/", views.UpdatedDocProfilePk, name="doc-profile-pk"),
    path("profile/<int:pk>/delete/", views.DeleteUserProfilePk, name="profile-delete"),
    path("profile/doc/<int:pk>/delete/", views.DeleteDocProfilePk, name="doc-profile-delete"),
]

appointment/models.py
from django.db import models
from django.contrib.auth import get_user_model
User = get_user_model()

# Create your models here.
class Appointment(models.Model):
    date = models.DateField()
    time = models.TimeField()
    status = models.CharField(choices=[('Pending', 'Pending'), ('Completed', 'Completed')], max_length=10)
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient')
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor')

    def __str__(self):
        return "Patient - {} Doc- {} At {} {}".format(self.patient, self.doctor, self.date, self.time)


class Prescription(models.Model):
    doctor = models.ForeignKey(User, on_delete=models.CASCADE, related_name='doctor_prescription')
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name='patient_prescription')
    date = models.DateField(auto_now_add=True)
    symptoms = models.CharField(max_length=200)
    prescription = models.TextField()

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return "Presciption Doc-{} Patient-{}".format(self.doctor, self.patient)

PAYMENT_TYPES = [
    ('I','Individual'),
    ('C','Consulting')
]

class Payment(models.Model):
    patient = models.ForeignKey(User, on_delete=models.CASCADE, related_name="patient_payments")
    date = models.DateField(auto_now_add=True)
    paid = models.IntegerField(null=True)
    outstanding = models.IntegerField(null=True)
    total = models.IntegerField(null=True)
    payment_type = models.CharField(choices=PAYMENT_TYPES, max_length=1, default="I")

    class Meta:
        ordering = ('-id',)

    def __str__(self):
        return "Payment Patient-{} Amount-{}".format(self.patient, self.total)

appointment/forms.py
from django import forms
from .models import *
from django.contrib.auth import get_user_model
User = get_user_model()

class PrescriptionForm(forms.ModelForm):

    class Meta:
        model = Prescription
        fields = ('patient', 'symptoms', 'prescription')

    def __init__(self, *args, **kwargs):
        super(PrescriptionForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['patient'].queryset = User.objects.filter(user_type="P")


class AppointmentForm(forms.ModelForm):

    class Meta:
        model = Appointment
        fields = '__all__'

    def __init__(self, *args, **kwargs):
        super(AppointmentForm, self).__init__(*args, **kwargs)
        if self.instance:
            self.fields['patient'].queryset = User.objects.filter(user_type="P")
            self.fields['doctor'].queryset = User.objects.filter(user_type="D")
            self.fields["date"].label = "Date (YYYY-MM-DD)"
            self.fields["time"].label = "Time 24 hr (HH:MM)"
        

appointment/views.py
from django.shortcuts import render, redirect
from .models import * 
from .forms import * 
from django.views.generic import ListView, CreateView
from django.urls import reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from user_profile.models import UserProfile
# Create your views here.

class AppointmentsForAPatientView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'account:login'

    def get_queryset(self):
        return Appointment.objects.filter(patient=self.request.user)


class AppointmentsForADoctorView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'account:login'

    def get_queryset(self):
        return Appointment.objects.filter(doctor=self.request.user)


class MedicalHistoryView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'account:login'

    def get_queryset(self):
        return Prescription.objects.filter(patient=self.request.user)


class PrescriptionListView(LoginRequiredMixin, ListView):
    login_url = '/login/'
    redirect_field_name = 'account:login'

    def get_queryset(self):
        return Prescription.objects.filter(doctor=self.request.user)


@login_required(login_url='/login/')
def PrescriptionCreateView(request):
    if request.method == 'POST':
        form = PrescriptionForm(request.POST)
        if form.is_valid():
            prescription = form.save(commit=False)
            prescription.doctor = request.user
            prescription.save()
            return redirect('appointment:doc-prescriptions')
    else:
        form = PrescriptionForm()
    return render(request, 'appointment/prescription_create.html', {'form': form})


@login_required(login_url='/login/')
def AppointmentCreateView(request):
    if request.method == 'POST':
        form = AppointmentForm(request.POST)
        if form.is_valid():
            appointment = form.save(commit=False)
            appointment.save()
            return redirect('appointment:r_dashboard')
    else:
        form = AppointmentForm()
    return render(request, 'appointment/appointment_create.html', {'form': form})


@login_required(login_url='/login/')
def rdashboard(request):
    if request.method == "GET" and request.user.user_type == "R":
        context = {
            "totalApp" : len(Appointment.objects.all()),
            "compApp" : len(Appointment.objects.filter(status="Completed")),
            "pendApp" : len(Appointment.objects.filter(status="Pending")),
            "app_list" : Appointment.objects.all(),
            "pat_list" : UserProfile.objects.filter(user__user_type="P")[:5]
        }
        return render(request, 'appointment/r_dashboard.html', context=context)


@login_required(login_url='/login/')
def hrdashboard(request):
    if request.method == "GET" and request.user.user_type == "HR":
        context = {
            "totalPat" : len(User.objects.filter(user_type="P")),
            "totalDoc" : len(User.objects.filter(user_type="D")),
            "ondutyDoc" : len(UserProfile.objects.filter(status="Active").filter(user__user_type="D")),
            "doc_list" : UserProfile.objects.filter(user__user_type="D")
        }
        return render(request, 'appointment/hr_dashboard.html', context=context)


@login_required(login_url='/login/')
def hraccounting(request):
    if request.method == "GET" and request.user.user_type == "HR":
        context = {
            "payment_ind" : Payment.objects.filter(payment_type="I"),
            "payment_cons" : Payment.objects.filter(payment_type="C"),
        }
        return render(request, 'appointment/accounting.html', context=context)


@login_required(login_url='/login/')
def pateintpayments(request):
    if request.method == "GET":
        context = {
            "payment_me" : Payment.objects.filter(patient=request.user),
        }
        return render(request, 'appointment/payment_invoice.html', context=context)


    

appointment/templates/appointment/accounting.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
    <div class="col-md-5">
        <h3>Individuals' Outstandings</h3>
        <div class="card card-body">
            <table class="table table-striped">
                <thead> 
                    <th>Patient</th>
                    <th>Outstanding</th>
                    <th>Paid</th>
                    <th>Reminder</th>
                </thead>
                {% for obj in payment_ind %}
                <tr>
                    <td>{{ obj.patient }}</td>
                    <td>{{ obj.outstanding }}</td>
                    <td>{{ obj.paid }}</td>
                    <td><button class="btn btn-primary">Set Reminder</button></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <div class="col-md-7">
        <h3>Consultings' Outstandings</h3>
        <div class="card card-body">
            <table class="table table-striped">
                <thead> 
                    <th>Date</th>
                    <th>Patient Name</th>
                    <th>Paid</th>
                    <th>Outstanding</th>
                    <th>Total</th>
                    <th>Invoice</th>
                </thead>
                {% for obj in payment_cons %}
                <tr>
                    <td>{{ obj.date }}</td>
                    <td>{{ obj.patient }}</td>
                    <td>{{ obj.paid }}</td>
                    <td>{{ obj.outstanding }}</td>
                    <td>{{ obj.total }}</td>
                    <td><a href="">Open Invoice</a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

appointment/templates/appointment/appointment_create.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h2>Create an Appointment</h2>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-default">
    </form>
</div>
{% endblock %}

appointment/templates/appointment/appointment_list.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h2>Your Appointments</h2>
    <div>
        {% if user.is_patient %}
        <table class="table table-striped">
            <thead>
                <th>Date</th>
                <th>Time</th>
                <th>Consulting Doctor</th>
                <th>Status</th>
            </thead>
            {% for obj in object_list %}
            <tr>
                <td>{{ obj.date }}</td>
                <td>{{ obj.time }}</td>
                <td>{{ obj.doctor }}</td>
                <td>{{ obj.status }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
        {% if user.is_doctor %}
        <table class="table table-striped">
            <thead>
                <th>Date</th>
                <th>Time</th>
                <th>Patient Info</th>
            </thead>
            {% for obj in object_list %}
            <tr>
                <td>{{ obj.date }}</td>
                <td>{{ obj.time }}</td>
                <td>{{ obj.patient }}</td>
            </tr>
            {% endfor %}
        </table>
        {% endif %}
    </div>  
</div>
{% endblock %}

appointment/templates/appointment/hr_dashboard.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1 align="center">Dashboard</h1>
    <br>
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Total Doctors</strong> - {{ totalDoc }}
        </li>
        <li class="list-group-item">
            <strong>Total Patients</strong> - {{ totalPat }}
        </li>
        <li class="list-group-item">
            <strong>On Duty Doctors</strong> - {{ ondutyDoc }}
        </li>  
    </ul>
</div>
<div class="row">
    <div class="col-md-12">
        <h3>Doctors</h3>
        <div class="card card-body">
            <table class="table table-striped">
                <thead> 
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Age</th>
                    <th>Status</th>
                    <th>Department</th>
                    <th>Attendance</th>
                    <th>Salary</th>
                    <th>Update</th>
                    <th>Remove</th>
                </thead>
                {% for obj in doc_list %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.phone }}</td>
                    <td>{{ obj.email }}</td>
                    <td>{{ obj.gender }}</td>
                    <td>{{ obj.age }}</td>
                    <td>{{ obj.status }}</td>
                    <td>{{ obj.department }}</td>
                    <td>{{ obj.attendance }}</td>
                    <td>{{ obj.salary }}</td>
                    <td><a href="{% url 'user_profile:doc-profile-pk' pk=obj.user.id %}"><button class="btn btn-warning">Update</button></a></td>
                    <td><a href="{% url 'user_profile:doc-profile-delete' pk=obj.user.id %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

appointment/templates/appointment/payment_invoice.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="row">
    <div class="col-md-12">
        <h3>Your Payments & Invoices</h3>
        <br>
        <div class="card card-body">
            <table class="table table-striped">
                <thead> 
                    <th>Invoice</th>
                    <th>Paid</th>
                    <th>Date</th>
                    <th>Outstanding</th>
                </thead>
                {% for obj in payment_me %}
                <tr>
                    <td><a href="">Open Invoice</a></td>
                    <td>{{ obj.paid }}</td>
                    <td>{{ obj.date }}</td>
                    <td>{{ obj.outstanding }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}

appointment/templates/appointment/prescription_create.html
{% extends "base.html" %}
{% load bootstrap3 %}


{% block content %}
<div class="container">
    <h2>Hello, {{ user.username }}</h2>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Create" class="btn btn-default">
    </form>
</div>
{% endblock %}

appointment/templates/appointment/prescription_list.html
{% extends "base.html" %}
{% load bootstrap3 %}

{% block content %}
<div class="container">
    {% if user.is_patient %}
    <h2>Your Medical History</h2>
    <br>
    <ul class="list-group">
        {% for obj in object_list %}
        <li class="list-group-item">
            <h3><strong>{{ obj.date }}</strong></h3>
            <p>Symptoms - {{ obj.symptoms }}</p>
            <p>Prescription - {{ obj.prescription }}</p>
            <button class="btn btn-primary">Learn More</button>
        </li>
        {% endfor %}
    {% endif %}
    {% if user.is_doctor %}
    <h2>Your Prescriptions</h2>
    <a href="{% url 'appointment:doc-prescriptions-create' %}"><button class="btn btn-primary pull-right">Create New Prescription</button></a>
    <br> <br>
    <ul class="list-group">
        {% for obj in object_list %}
        <li class="list-group-item">
            <h3><strong>{{ obj.date }}</strong></h3>
            <p>Symptoms - {{ obj.symptoms }}</p>
            <p>Prescription - {{ obj.prescription }}</p>
            <p>Patient Name - {{ obj.patient }}</p>
        </li>
        {% endfor %}
    {% endif %}
    </ul>
</div>
{% endblock %}

appointment/templates/appointment/r_dashboard.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}
<div class="container">
    <h1 align="center">Dashboard</h1>
    <br>
    <ul class="list-group">
        <li class="list-group-item">
            <strong>Total Appointments</strong> - {{ totalApp }}
        </li>
        <li class="list-group-item">
            <strong>Appointments Done</strong> - {{ compApp }}
        </li>
        <li class="list-group-item">
            <strong>Upcoming Appointments</strong> - {{ pendApp }}
        </li>  
    </ul>
</div>
<div class="row">
    <div class="col-md-5">
        <h3>Appointments -</h3>
        <div class="card card-body">
            <a href="{% url 'appointment:appointment-create' %}"><button class="btn btn-primary">Create Appointment</button></a>
            <table class="table table-striped">
                <thead>
                    <th>Date</th>
                    <th>Time</th>
                    <th>Doctor</th>
                    <th>Patient</th>
                    <th>Status</th>
                </thead>
                {% for obj in app_list %}
                <tr>
                    <td>{{ obj.date }}</td>
                    <td>{{ obj.time }}</td>
                    <td>{{ obj.doctor }}</td>
                    <td>{{ obj.patient }}</td>
                    <td>{{ obj.status }}</td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
    <br>
    <div class="col-md-7">
        <h3>Last 5 Patients -</h3>
        <div class="card card-body">
            <a href="{% url 'user_profile:profile-create' %}"><button class="btn btn-primary">Create Patient</button></a>
            <table class="table table-striped">
                <thead> 
                    <th>Name</th>
                    <th>Phone</th>
                    <th>Email</th>
                    <th>Gender</th>
                    <th>Age</th>
                    <th>Update</th>
                    <th>Remove</th>
                </thead>
                {% for obj in pat_list %}
                <tr>
                    <td>{{ obj.name }}</td>
                    <td>{{ obj.phone }}</td>
                    <td>{{ obj.email }}</td>
                    <td>{{ obj.gender }}</td>
                    <td>{{ obj.age }}</td>
                    <td><a href="{% url 'user_profile:profile-pk' pk=obj.user.id %}"><button class="btn btn-warning">Update</button></a></td>
                    <td><a href="{% url 'user_profile:profile-delete' pk=obj.user.id %}"><button class="btn btn-danger">Delete</button></a></td>
                </tr>
                {% endfor %}
            </table>
        </div>
    </div>
</div>
{% endblock %}