account/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "account"

urlpatterns = [
    path("login/", auth_views.LoginView.as_view(template_name="account/login.html"),name='login'),
    path("logout/", auth_views.LogoutView.as_view(template_name="account/logout.html"), name="logout"),
    path("register/", views.SignUp, name="signup"),
    path("", views.home, name="home"),
    path("aboutus/", views.aboutus, name="about-us"),
    path("contact/", views.contact, name="contact"),
]

appointment/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "appointment"

urlpatterns = [
    path("appointments/p/", views.AppointmentsForAPatientView.as_view(), name="patient-appointments"),
    path("appointments/d/", views.AppointmentsForADoctorView.as_view(), name="doctor-appointments"),
    path("medHistory/", views.MedicalHistoryView.as_view(), name="med-history"),
    path("prescriptions/", views.PrescriptionListView.as_view(), name="doc-prescriptions"),
    path("prescription/create", views.PrescriptionCreateView, name="doc-prescriptions-create"),
    path("appointment/create", views.AppointmentCreateView, name="appointment-create"),
    path("rdashboard/", views.rdashboard, name="r_dashboard"),
    path("hrdashboard/", views.hrdashboard, name="hr_dashboard"),
    path("hraccounting/", views.hraccounting, name="hr_accounting"),
    path("payments/", views.pateintpayments, name="pat_payments"),
]

hospital/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include('account.urls', namespace="account")),
    path("", include('user_profile.urls', namespace="user_profile")),
    path("", include('appointment.urls', namespace="appointment")),
    # ... the rest of your URLconf goes here ...
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

user_profile/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = "user_profile"

urlpatterns = [
    path("profile/", views.UpdatedUserProfile, name="profile"),
    path("profile/create/", views.CreateUserProfile, name="profile-create"),
    path("profile/<int:pk>/", views.UpdatedUserProfilePk, name="profile-pk"),
    path("profile/doc/<int:pk>/", views.UpdatedDocProfilePk, name="doc-profile-pk"),
    path("profile/<int:pk>/delete/", views.DeleteUserProfilePk, name="profile-delete"),
    path("profile/doc/<int:pk>/delete/", views.DeleteDocProfilePk, name="doc-profile-delete"),
]

templates/base.html
<!DOCTYPE html>
{% load static %}
<html>
  <head>
    <meta charset="utf-8">
    <title>Hospital</title>
    <!-- Latest compiled and minified CSS -->

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

    <!-- Optional theme -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <!-- Latest compiled and minified JavaScript -->
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>


    <link href="https://fonts.googleapis.com/css?family=Montserrat" rel="stylesheet">


  </head>


  <body>

    <nav class="navbar navbar-inverse" role="navigation" id="navbar">
    			<div class="container">

            <a class="navbar-brand mynav" href="{% url 'account:home' %}">Hospital Management System</a>

    					<ul class="nav navbar-nav navbar-right mynav">
    						{% if user.is_authenticated %}
                      {% if user.is_doctor %}
                      <!-- doctor's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'user_profile:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'appointment:doctor-appointments' %}"class="btn btn-simple">Appointments</a></li>
                      <li><a href="{% url 'appointment:doc-prescriptions' %}"class="btn btn-simple">Prescriptions</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li>
                      {% endif %}
                      {% if user.is_patient %}
                      <!-- patient's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'appointment:patient-appointments' %}"class="btn btn-simple">Your Appointment's</a></li>
                      <li><a href="{% url 'appointment:pat_payments' %}"class="btn btn-simple">Invoices and Payments</a></li>
                      <li><a href="{% url 'user_profile:profile' %}" class="btn btn-simple">Profile</a></li>
                      <li><a href="{% url 'appointment:med-history' %}"class="btn btn-simple">Medical History</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li> 
                      {% endif %}
                      {% if user.is_receptionist %}
                      <!-- receptionist's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'appointment:r_dashboard' %}"class="btn btn-simple">Dashboard</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li> 
                      {% endif %}
                      {% if user.is_HR %}
                      <!-- HR's dashboard -->
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'appointment:hr_dashboard' %}"class="btn btn-simple">Dashboard</a></li>
                      <li><a href="{% url 'appointment:hr_accounting' %}"class="btn btn-simple">Accounting</a></li>
    						      <li><a href="{% url 'account:logout' %}" class="btn btn-simple"><button class="btn btn-warning">Log Out</button></a></li> 
                      {% endif %}
    						{% else %}
                      <li><a href="{% url 'account:home' %}"class="btn btn-simple">Home</a></li>
                      <li><a href="{% url 'account:about-us' %}"class="btn btn-simple">About Us</a></li>
                      <li><a href="{% url 'account:contact' %}"class="btn btn-simple">Contact</a></li>
                      <li><a href="{% url 'account:signup' %}" class="btn btn-simple">Register</a></li>
    						      <li><a href="{% url 'account:login' %}" class="btn btn-simple"><button class="btn btn-success">Log In</button></a></li>   
    						{% endif %}
    					</ul>
    			</div>
    		</nav>
        <div class="container mycontent">
          {% block content %}

          {% endblock %}

        </div>



<canvas id="canvas"></canvas>



  </body>
  
</html>

templates/index.html
{% extends "base.html" %}
{% block content %}

    <h1>Welcome to Star Social!</h1>
    <h3>The one of the finest in its category </h3>
   

{% endblock %}